### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by arialcrime** [arialcrime/CaseChanger#1]
```
Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 131, in callObserver_withMethod_forEvent_withInfo_
  File "CaseChanger.py", line 22, in addButton
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/vanilla/vanillaGroup.py", line 86, in __setattr__
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/vanilla/vanillaBase.py", line 27, in __setattr__
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/vanilla/vanillaBase.py", line 283, in _setAttr
AssertionError: can't replace vanilla attribute
```

Need to investigate why this happens and where it comes from.

**Comment by arialcrime** [comment]
Did I simply mess up my observer setup, or does it have to do with something within Vanilla? @typesupply @typemytype

**Comment by typemytype** [comment]
you can not replace existing vanilla views...

so you either have to test if your controls are already present when opening a space center or `del` the control from the space center on close.

Now you are just removing the observer, which is good...

**Comment by arialcrime** [comment]
Thanks for the quick reply, I will have a look.
